{
    developer: "GApps",
    id: "drmacinyasha",
    summary: "Google Apps Add-on for CyanogenMod and other ROMs",
    manifest: "http://drmacinyasha.github.com/proprietary_vendor_google/manifest.js",
    roms:
    {
        blade: true,
        bravo: true,
        bravoc: true,
        buzz: true,
        click: true,
        crespo: true,
        desirec: true,
        dream_sapphire: true,
        encore: true,
        epic: true,
        espresso: true,
        glacier: true,
        harmony: true,
        hero: true,
        heroc: true,
        inc: true,
        legend: true,
        leo: true,
        liberty: true,
        one: true,
        passion: true,
        sholes: true,
        streak: true,
        supersonic: true,
        vega: true,
        vibrant: true,
        vision: true,
        z71: true,
        zero: true
    }
}